# Generated by Django 5.0.3 on 2024-03-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salariale', '0002_departement_remove_salary_employee_employer_salaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='name',
            new_name='nom',
        ),
    ]
